name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Setup Dynamic Env
        run: |
          sudo apt update
          sudo apt install -y build-essential git ccache python3-dev python3-pip libffi-dev zlib1g-dev libssl-dev openjdk-17-jdk unzip python3-virtualenv

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v3
        with:
          buildozer_version: stable
          command: buildozer android debug
          repository_root: .
